version: '3.8'

services:
  teamcity-agent:
    image: jetbrains/teamcity-agent:latest
    container_name: teamcity-agent
    restart: unless-stopped
    environment:
      - SERVER_URL=https://teamcity.chaosrex.com
      - AGENT_NAME=docker-agent-chaosrex
    volumes:
      - agent_conf:/data/teamcity_agent/conf
      - agent_logs:/opt/teamcity-agent/logs
    networks:
      - teamcity-net

volumes:
  agent_conf:
  agent_logs:

networks:
  teamcity-net:
    driver: bridge