version: '3.8'

services:
  teamcity-agent:
    build:
      context: .
      dockerfile: Dockerfile
    image: jetbrains/teamcity-agent:latest
    container_name: teamcity-agent
    restart: unless-stopped
    environment:
      - SERVER_URL=http://66.179.253.124:8111
      - AGENT_NAME=public-agent-chaosrex
    extra_hosts:
      - "teamcity.chaosrex.com:66.179.253.124"
    volumes:
      - agent_conf:/data/teamcity_agent/conf
      - agent_logs:/opt/teamcity-agent/logs
    networks:
      - teamcity-net

volumes:
  agent_conf:
  agent_logs:

networks:
  teamcity-net:
    driver: bridge
